### ISSUE TITLE
percySnapshot fails silently

### ISSUE THREAD

**Issue by rtpg** [percy/percy-selenium-python#10]
Right now there's not really a way to know that a call to `percySnapshot` succeeds in the test run.

 I think that a default behaviour of failing when the connection fails would make things easier to debug in general

**Comment by Robdel12** [comment]
Hey @rtpg! This is done by design, so tests can be ran without Percy being enabled. There also isn't anything to return from `percySnapshot` since it's `POST`'ing DOM over to a different process (which then eventually turns into a screenshot from our API). The results for this isn't known until the tests are finished though, so it wouldn't be possible to fail on diff here either. 

Curious to hear more about what you're running into and if we can solve it in a different way

**Comment by rtpg** [comment]
Basically I just had the issue of trying to set things up, having things pass despite the percy agent not running, and being a bit confused about why nothing was showing up.

Thinking about it a bit more, I understand the rationale of at least providing a mechanism for silently falling through. But I do think that in a CI build, a failure to connect to the percy agent locally does feel like something we would want to trigger a build failure by default (since it could be an indicator of some issue with the build pipeline).

I 100% understand not failing on a diff, both for the reasons you mentioned and because the "human review of diff" aspect is kinda... the whole point of this, right?
